baseURL = 'https://RyoheiKamei.github.io/'
languageCode = 'en-us'
theme = "aafu"
publishDir = "docs"



[build]
  writeStats = true

[params]
    title = "Ryohei Kamei(Tohoku University)/亀井遼平(東北大学)"
    author = "Ryohei Kamei"
    description = "Ryohei Kamei Homepage/亀井遼平のホームページ"
    copyright = "short copyright message"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "ocean"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Ryohei Kamei"
        tagline = "亀井 遼平"
        location = "Tohoku NLP Group"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"


        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/RyoheiKamei"
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-twitter"
            url = "https://twitter.com/ka_me1024"
            title = "Twitter"


    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "award"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "1st year master's student of Graduate School of Information Sciences, Tohoku University @Tohoku NLP Group"

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

#        [[params.experience.list]]
#            position = "Job Title"
#            dates = "2019 - *Present*"
#            company = "Company Name"
#            details = "Printed from desktop. Sent [emails](#). Called people using telephone. Drank water from office cooler. Ate donuts on people's birthdays."
#        [[params.experience.list]]
#            position = "Job Title"
#            dates = "2018 - 2019"
#            url = "#"
#            company = "Company Name"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "M.S. in Information Science"
            college = "Tohoku University"
            dates = "2023 - "


        [[params.education.list]]
            degree = "B.E. in Computer Science"
            college = "Tohoku University"
            dates = "2019 - 2023"

        [[params.education.list]]
            degree = "High School"
            college = "Sendai Second High School"
            dates = "2016 - 2019"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

    [[params.publication.list]]
        title = "柔らかいジャンプ付き編集距離に向けて"
        authors = "亀井遼平, 横井祥, 仲村祐希, 渡辺太郎, 乾健太郎"
        date = "2023"
        journal = "Annual Meetings of the Association for Natural Language Processing"
        url = "https://www.anlp.jp/proceedings/annual_meeting/2023/pdf_dir/C5-3.pdf"
        type = "Proceedings"

    [[params.publication.list]]
        title = "生成応答に含まれる事実に基づかない情報の自動検出の試み"
        authors = "亀井遼平, 塩野大輝, 赤間怜奈, 鈴木潤"
        date = "2023"
        journal = "The Young Researcher Association for NLP Studies"
#         url = "#"
        type = "Proceedings"

    [[params.publication.list]]
        title = "Hagi bot: LLMを用いた対話状態追跡と人間らしい振る舞いで自然な議論を行うマルチモーダル対話システム"
        authors = "中野 雄斗、野末 慎之介、穀田 一真、有山 知希、佐藤 魁、曾根 周作、亀井 遼平、謝 素春、成田 風香、守屋 彰二、赤間 怜奈、松林 優一郎、坂口 慶祐"
        date = "2023"
        journal = "The Japanese Society for Artificial Intelligence Special Interest Group on Spoken Language Understanding and Dialogue Processing"
        url = "https://www.jstage.jst.go.jp/article/jsaislud/99/0/99_102/_article/-char/ja/"
        type = "Proceedings"


    [[params.publication.list]]
        title = "事実正誤判定が不要な生成応答の検出に向けたデータセットの収集と分析"
        authors = "亀井遼平, 塩野大輝, 赤間怜奈, 鈴木潤"
        date = "2024"
        journal = "Annual Meetings of the Association for Natural Language Processing"
        url = "https://www.anlp.jp/proceedings/annual_meeting/2024/pdf_dir/B8-3.pdf"
        type = "Proceedings"

    # Award section
    [params.award]
        title = "Awards"
        icon = "fas fa-trophy"
        [[params.award.list]]
            title = "NLP若手の会 (YANS) 第18回シンポジウム 奨励賞"
            url = "https://yans.anlp.jp/entry/award"
        
        [[params.award.list]]
            title = "NLP若手の会 (YANS) 第18回シンポジウム スポンサー賞 サイバーエージェント賞"
            url = "https://yans.anlp.jp/entry/award"

        [[params.award.list]]
            title = "NLP若手の会 (YANS) 第18回シンポジウム ハッカソン賞 デモアプリ開発ハッカソン　優秀賞"
            url = "https://yans.anlp.jp/entry/award"

        [[params.award.list]]
            title = "NLP若手の会 (YANS) 第18回シンポジウム ハッカソン賞 デモアプリ開発ハッカソン　審査員特別賞"
            url = "https://yans.anlp.jp/entry/award"

        [[params.award.list]]
            title = "第99回 人工知能学会言語・音声理解と対話処理研究会 第6回対話システムライブコンペティション 最優秀賞"
            url = "https://sites.google.com/view/dslc6/%E7%B5%90%E6%9E%9C?authuser=0"




    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "東北社会課題解決型クリエーター発掘・育成プログラム SICA (Social Impact Creators' Accelerator)"
            url = "https://sica-tohoku.com/"

#         [[params.project.list]]
#             title = "NLP 100 Knocks"
#             url = "https://nlp100.github.io/ja/"
#             description = "Learning NLP with Python"
#         [[params.project.list]]
#             title = "Learning Fundamentals of NLP"
#             url = "https://www.nlp.ecei.tohoku.ac.jp/study-groups/learning-fundamentals-of-nlp/"
#             description = "Learning NLP"




    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Python:fluent"
            skillrating = 75
        [[params.skill.list]]
            skill = "English/TOEIC: 885"
            skillrating = 89.3


    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Watching Sports"
        [[params.hobby.list]]
            hobby = "Reading Books"